### ISSUE TITLE
preact-svg@1.5.0  <svg> attribute height: Expected length, "undefined".

### ISSUE THREAD

**Issue by eisneim** [developit/preact-svg#17]
https://jsfiddle.net/eisneim/e5ssp6pn/3/
see console

**Comment by developit** [comment]
Thanks, looking into it.

**Comment by developit** [comment]
@eisneim Looks like the fix for [this issue](https://github.com/developit/preact-svg/commit/100d05f62064600355ff84a30285277ce28d8700#commitcomment-17411136) resolves this, and is now released as `preact-svg@1.5.1`.  Sorry for the botched `1.5.0` release!

**Comment by eisneim** [comment]
@developit yeah, me and zhenkunou discussed about that, you have done a great job with preact, pls keep it up!

**Comment by developit** [comment]
Awesome, can't Hank you guys enough. Cheers!
