### ISSUE TITLE
use lowercase svg

### ISSUE THREAD

**Issue by aeosynth** [developit/preact-svg#19]
i'm sure there's a reason for naming the class `SVG` (all caps), but i would really like to use lowercase instead, like in react

**Comment by developit** [comment]
The caps are to switch from string to component. However, I agree and I'm working in an elegant patch style solution, similar to how it works in preact-compat.

**Comment by developit** [comment]
@aeosynth There's currently a discussion about bundling SVG support into Preact itself, which would mean just using normal `<svg>` tags, with Preact handling the differences.  Would love your opinion there: https://github.com/developit/preact/issues/195

**Comment by developit** [comment]
@aeosynth Since SVG support is now built into Preact itself as of `preact@5.1.0-beta.16`, this now works!  Let me know if you run into anything.

**Comment by aeosynth** [comment]
neat, thanks
