### ISSUE TITLE
Apparent bug on IE11

### ISSUE THREAD

**Issue by mkxml** [developit/preact-svg#2]
Hello.

Apparently there is a bug when rendering svgs on IE11. Anyone else can report this?

From my tests I found out that in the `defineProperty` loop IE11 seems to reject the `viewport` property.

It appears to be the only property it rejects raising an error. The screenshot below show a hack that just skips that property and then everything works fine including all my preact components and stuff.

![screen1](https://cloud.githubusercontent.com/assets/1051644/12756721/1dea0de6-c9bc-11e5-8197-ae293a9603ee.jpg)

I couldn't reproduce this on MS Edge or on any other modern browsers, I didn't test on IE versions prior to 11 though.

The screenshot below shows the IE11 throwing the error in my code:

![screen2](https://cloud.githubusercontent.com/assets/1051644/12756644/cdb18c96-c9bb-11e5-8218-2208f3063688.jpg)

For now I'm using my hack since it does affect my use case. I don't know exactly if `viewport` is needed here for other people or how else we should tackle this.

**Comment by developit** [comment]
Hi @mkautzmann - great bug report, thank you for the helpful screen captures and context.  One additional detail that would help me diagnose would be the value of `el.nodeName` at the time of the exception.  If the issue ocurrs on `svg` nodes themselves, then it's a more difficult fix. If it's being triggered on any other type of element, I can simply add a conditional similar to yours.

Cheers!

**Comment by mkxml** [comment]
`el.nodeName` is `svg` at the exception. I'm rendering other elements with preact in the page but IE blocks the rendering on all elements because of this `preact-svg` bug. It must be something hardcoded in IE that doesn't accept `viewport` property definition on svg.

**Comment by developit** [comment]
@mkautzmann Since most browsers are not affected by this, I think the best solution would be to wrap the property assignment in a try/catch.  It won't be the best for performance, but it will mean `viewport` can still be adjusted dynamically in 99% of browsers.

**Comment by mkxml** [comment]
@developit Looks fine. I can do that and submit a PR if you find that OK. It may stay around as long as IE11 is relevant. Edge does not have the issue.

**Comment by developit** [comment]
That would be awesome, I'll merge and release right away if you have the time.

**Comment by developit** [comment]
Fix released in `1.3.0`
